apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-file-receiver-dev
  namespace: productos-dev
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
