apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-file-receiver-dev
  namespace: productos-dev
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
